using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Athena.Core.Patchables
{
    public class Descriptors
    {
        public enum WoWObjectFields
        {
            Guid = 0x0,
            Data = 0x8,
            Type = 0x10,
            EntryID = 0x14,
            DynamicFlags = 0x18,
            Scale = 0x1C,
        };

        public enum WoWItemFields
        {
            Owner = 0x20,
            ContainedIn = 0x28,
            Creator = 0x30,
            GiftCreator = 0x38,
            StackCount = 0x40,
            Expiration = 0x44,
            SpellCharges = 0x48,
            DynamicFlags = 0x5C,
            Enchantment = 0x60,
            PropertySeed = 0xFC,
            RandomPropertiesID = 0x100,
            Durability = 0x104,
            MaxDurability = 0x108,
            CreatePlayedTime = 0x10C,
            ModifiersMask = 0x110,
        };

        public enum WoWContainerFields
        {
            Slots = 0x114,
            NumSlots = 0x234,
        };

        public enum WoWUnitFields
        {
            Charm = 0x20,
            Summon = 0x28,
            Critter = 0x30,
            CharmedBy = 0x38,
            SummonedBy = 0x40,
            CreatedBy = 0x48,
            DemonCreator = 0x50,
            Target = 0x58,
            BattlePetCompanionGUID = 0x60,
            ChannelObject = 0x68,
            ChannelSpell = 0x70,
            SummonedByHomeRealm = 0x74,
            Sex = 0x78,
            DisplayPower = 0x7C,
            OverrideDisplayPowerID = 0x80,
            Health = 0x84,
            Power = 0x88,
            MaxHealth = 0x9C,
            MaxPower = 0xA0,
            PowerRegenFlatModifier = 0xB4,
            PowerRegenInterruptedFlatModifier = 0xC8,
            Level = 0xDC,
            EffectiveLevel = 0xE0,
            FactionTemplate = 0xE4,
            VirtualItemID = 0xE8,
            Flags = 0xF4,
            Flags2 = 0xF8,
            AuraState = 0xFC,
            AttackRoundBaseTime = 0x100,
            RangedAttackRoundBaseTime = 0x108,
            BoundingRadius = 0x10C,
            CombatReach = 0x110,
            DisplayID = 0x114,
            NativeDisplayID = 0x118,
            MountDisplayID = 0x11C,
            MinDamage = 0x120,
            MaxDamage = 0x124,
            MinOffHandDamage = 0x128,
            MaxOffHandDamage = 0x12C,
            AnimTier = 0x130,
            PetNumber = 0x134,
            PetNameTimestamp = 0x138,
            PetExperience = 0x13C,
            PetNextLevelExperience = 0x140,
            ModCastingSpeed = 0x144,
            ModSpellHaste = 0x148,
            ModHaste = 0x14C,
            ModRangedHaste = 0x150,
            ModHasteRegen = 0x154,
            CreatedBySpell = 0x158,
            NpcFlags = 0x15C,
            EmoteState = 0x164,
            Stats = 0x168,
            StatPosBuff = 0x17C,
            StatNegBuff = 0x190,
            Resistances = 0x1A4,
            ResistanceBuffModsPositive = 0x1C0,
            ResistanceBuffModsNegative = 0x1DC,
            BaseMana = 0x1F8,
            BaseHealth = 0x1FC,
            ShapeshiftForm = 0x200,
            AttackPower = 0x204,
            AttackPowerModPos = 0x208,
            AttackPowerModNeg = 0x20C,
            AttackPowerMultiplier = 0x210,
            RangedAttackPower = 0x214,
            RangedAttackPowerModPos = 0x218,
            RangedAttackPowerModNeg = 0x21C,
            RangedAttackPowerMultiplier = 0x220,
            MinRangedDamage = 0x224,
            MaxRangedDamage = 0x228,
            PowerCostModifier = 0x22C,
            PowerCostMultiplier = 0x248,
            MaxHealthModifier = 0x264,
            HoverHeight = 0x268,
            MinItemLevel = 0x26C,
            MaxItemLevel = 0x270,
            WildBattlePetLevel = 0x274,
            BattlePetCompanionNameTimestamp = 0x278,
            InteractSpellID = 0x27C,
        };

        public enum WoWPlayerFields
        {
            DuelArbiter = 0x280,
            PlayerFlags = 0x288,
            GuildRankID = 0x28C,
            GuildDeleteDate = 0x290,
            GuildLevel = 0x294,
            HairColorID = 0x298,
            RestState = 0x29C,
            ArenaFaction = 0x2A0,
            DuelTeam = 0x2A4,
            GuildTimeStamp = 0x2A8,
            QuestLog = 0x2AC,
            VisibleItems = 0xE64,
            PlayerTitle = 0xEFC,
            FakeInebriation = 0xF00,
            VirtualPlayerRealm = 0xF04,
            CurrentSpecID = 0xF08,
            TaxiMountAnimKitID = 0xF0C,
            CurrentBattlePetBreedQuality = 0xF10,
            InvSlots = 0xF14,
            FarsightObject = 0x11C4,
            KnownTitles = 0x11CC,
            Coinage = 0x11F4,
            XP = 0x11FC,
            NextLevelXP = 0x1200,
            Skill = 0x1204,
            CharacterPoints = 0x1904,
            MaxTalentTiers = 0x1908,
            TrackCreatureMask = 0x190C,
            TrackResourceMask = 0x1910,
            MainhandExpertise = 0x1914,
            OffhandExpertise = 0x1918,
            RangedExpertise = 0x191C,
            CombatRatingExpertise = 0x1920,
            BlockPercentage = 0x1924,
            DodgePercentage = 0x1928,
            ParryPercentage = 0x192C,
            CritPercentage = 0x1930,
            RangedCritPercentage = 0x1934,
            OffhandCritPercentage = 0x1938,
            SpellCritPercentage = 0x193C,
            ShieldBlock = 0x1958,
            ShieldBlockCritPercentage = 0x195C,
            Mastery = 0x1960,
            PvpPowerDamage = 0x1964,
            PvpPowerHealing = 0x1968,
            ExploredZones = 0x196C,
            RestStateBonusPool = 0x1C8C,
            ModDamageDonePos = 0x1C90,
            ModDamageDoneNeg = 0x1CAC,
            ModDamageDonePercent = 0x1CC8,
            ModHealingDonePos = 0x1CE4,
            ModHealingPercent = 0x1CE8,
            ModHealingDonePercent = 0x1CEC,
            ModPeriodicHealingDonePercent = 0x1CF0,
            WeaponDmgMultipliers = 0x1CF4,
            ModSpellPowerPercent = 0x1D00,
            ModResiliencePercent = 0x1D04,
            OverrideSpellPowerByAPPercent = 0x1D08,
            OverrideAPBySpellPowerPercent = 0x1D0C,
            ModTargetResistance = 0x1D10,
            ModTargetPhysicalResistance = 0x1D14,
            LifetimeMaxRank = 0x1D18,
            SelfResSpell = 0x1D1C,
            PvpMedals = 0x1D20,
            BuybackPrice = 0x1D24,
            BuybackTimestamp = 0x1D54,
            YesterdayHonorableKills = 0x1D84,
            LifetimeHonorableKills = 0x1D88,
            WatchedFactionIndex = 0x1D8C,
            CombatRatings = 0x1D90,
            PvpInfo = 0x1DFC,
            MaxLevel = 0x1E5C,
            RuneRegen = 0x1E60,
            NoReagentCostMask = 0x1E70,
            GlyphSlots = 0x1E80,
            Glyphs = 0x1E98,
            GlyphSlotsEnabled = 0x1EB0,
            PetSpellPower = 0x1EB4,
            Researching = 0x1EB8,
            ProfessionSkillLine = 0x1ED8,
            UiHitModifier = 0x1EE0,
            UiSpellHitModifier = 0x1EE4,
            HomeRealmTimeOffset = 0x1EE8,
            ModPetHaste = 0x1EEC,
            SummonedBattlePetGUID = 0x1EF0,
            OverrideSpellsID = 0x1EF8,
            LfgBonusFactionID = 0x1EFC,
            LootSpecID = 0x1F00,
            OverrideZonePVPType = 0x1F04,
            ItemLevelDelta = 0x1F08,
        };

        public enum WoWGameObjectFields
        {
            CreatedBy = 0x20,
            DisplayID = 0x28,
            Flags = 0x2C,
            ParentRotation = 0x30,
            FactionTemplate = 0x40,
            Level = 0x44,
            PercentHealth = 0x48,
            StateSpellVisualID = 0x4C,
        };

        public enum WoWDynamicObjectFields
        {
            Caster = 0x20,
            TypeAndVisualID = 0x28,
            SpellID = 0x2C,
            Radius = 0x30,
            CastTime = 0x34,
        };

        public enum WoWCorpseFields
        {
            Owner = 0x20,
            PartyGUID = 0x28,
            DisplayID = 0x30,
            Items = 0x34,
            SkinID = 0x80,
            FacialHairStyleID = 0x84,
            Flags = 0x88,
            DynamicFlags = 0x8C,
        };

        public enum WoWAreaTriggerFields
        {
            Caster = 0x20,
            Duration = 0x28,
            SpellID = 0x2C,
            SpellVisualID = 0x30,
            ExplicitScale = 0x34,
        };

        public enum WoWSceneObjectFields
        {
            ScriptPackageID = 0x20,
            RndSeedVal = 0x24,
            CreatedBy = 0x28,
            SceneType = 0x30,
        };

    }
}
