namespace Athena.Core.Patchables
{
    //Last updated: 6.0.1.18716
    public class Descriptors
    {
        public enum WoWObjectFields
        {
            Guid = 0x0,
            Data = 0x10,
            Type = 0x20,
            EntryID = 0x24,
            DynamicFlags = 0x28,
            Scale = 0x2C,
        };

        public enum WoWItemFields
        {
            Owner = 0x30,
            ContainedIn = 0x40,
            Creator = 0x50,
            GiftCreator = 0x60,
            StackCount = 0x70,
            Expiration = 0x74,
            SpellCharges = 0x78,
            DynamicFlags = 0x8C,
            Enchantment = 0x90,
            PropertySeed = 0x12C,
            RandomPropertiesID = 0x130,
            Durability = 0x134,
            MaxDurability = 0x138,
            CreatePlayedTime = 0x13C,
            ModifiersMask = 0x140,
            Context = 0x144,
        };

        public enum WoWContainerFields
        {
            Slots = 0x148,
            NumSlots = 0x388,
        };

        public enum WoWUnitFields
        {
            Charm = 0x30,
            Summon = 0x40,
            Critter = 0x50,
            CharmedBy = 0x60,
            SummonedBy = 0x70,
            CreatedBy = 0x80,
            DemonCreator = 0x90,
            Target = 0xA0,
            BattlePetCompanionGUID = 0xB0,
            BattlePetDBID = 0xC0,
            ChannelObject = 0xC8,
            ChannelSpell = 0xD8,
            SummonedByHomeRealm = 0xDC,
            Sex = 0xE0,
            DisplayPower = 0xE4,
            OverrideDisplayPowerID = 0xE8,
            Health = 0xEC,
            Power = 0xF0,
            MaxHealth = 0x108,
            MaxPower = 0x10C,
            PowerRegenFlatModifier = 0x124,
            PowerRegenInterruptedFlatModifier = 0x13C,
            Level = 0x154,
            EffectiveLevel = 0x158,
            FactionTemplate = 0x15C,
            VirtualItemID = 0x160,
            Flags = 0x16C,
            Flags2 = 0x170,
            Flags3 = 0x174,
            AuraState = 0x178,
            AttackRoundBaseTime = 0x17C,
            RangedAttackRoundBaseTime = 0x184,
            BoundingRadius = 0x188,
            CombatReach = 0x18C,
            DisplayID = 0x190,
            NativeDisplayID = 0x194,
            MountDisplayID = 0x198,
            MinDamage = 0x19C,
            MaxDamage = 0x1A0,
            MinOffHandDamage = 0x1A4,
            MaxOffHandDamage = 0x1A8,
            AnimTier = 0x1AC,
            PetNumber = 0x1B0,
            PetNameTimestamp = 0x1B4,
            PetExperience = 0x1B8,
            PetNextLevelExperience = 0x1BC,
            ModCastingSpeed = 0x1C0,
            ModSpellHaste = 0x1C4,
            ModHaste = 0x1C8,
            ModRangedHaste = 0x1CC,
            ModHasteRegen = 0x1D0,
            CreatedBySpell = 0x1D4,
            NpcFlags = 0x1D8,
            EmoteState = 0x1E0,
            Stats = 0x1E4,
            StatPosBuff = 0x1F8,
            StatNegBuff = 0x20C,
            Resistances = 0x220,
            ResistanceBuffModsPositive = 0x23C,
            ResistanceBuffModsNegative = 0x258,
            ModBonusArmor = 0x274,
            BaseMana = 0x278,
            BaseHealth = 0x27C,
            ShapeshiftForm = 0x280,
            AttackPower = 0x284,
            AttackPowerModPos = 0x288,
            AttackPowerModNeg = 0x28C,
            AttackPowerMultiplier = 0x290,
            RangedAttackPower = 0x294,
            RangedAttackPowerModPos = 0x298,
            RangedAttackPowerModNeg = 0x29C,
            RangedAttackPowerMultiplier = 0x2A0,
            MinRangedDamage = 0x2A4,
            MaxRangedDamage = 0x2A8,
            PowerCostModifier = 0x2AC,
            PowerCostMultiplier = 0x2C8,
            MaxHealthModifier = 0x2E4,
            HoverHeight = 0x2E8,
            MinItemLevelCutoff = 0x2EC,
            MinItemLevel = 0x2F0,
            MaxItemLevel = 0x2F4,
            WildBattlePetLevel = 0x2F8,
            BattlePetCompanionNameTimestamp = 0x2FC,
            InteractSpellID = 0x300,
            StateSpellVisualID = 0x304,
            StateAnimID = 0x308,
            StateAnimKitID = 0x30C,
            StateWorldEffectID = 0x310,
            ScaleDuration = 0x320,
            LooksLikeMountID = 0x324,
            LooksLikeCreatureID = 0x328,
        };

        public enum WoWPlayerFields
        {
            DuelArbiter = 0x32C,
            WowAccount = 0x33C,
            PlayerFlags = 0x34C,
            PlayerFlagsEx = 0x350,
            GuildRankID = 0x354,
            GuildDeleteDate = 0x358,
            GuildLevel = 0x35C,
            HairColorID = 0x360,
            RestState = 0x364,
            ArenaFaction = 0x368,
            DuelTeam = 0x36C,
            GuildTimeStamp = 0x370,
            QuestLog = 0x374,
            VisibleItems = 0xF2C,
            PlayerTitle = 0x1010,
            FakeInebriation = 0x1014,
            VirtualPlayerRealm = 0x1018,
            CurrentSpecID = 0x101C,
            TaxiMountAnimKitID = 0x1020,
            AvgItemLevelTotal = 0x1024,
            AvgItemLevelEquipped = 0x1028,
            CurrentBattlePetBreedQuality = 0x102C,
            InvSlots = 0x1030,
            FarsightObject = 0x1BB0,
            KnownTitles = 0x1BC0,
            Coinage = 0x1BE8,
            XP = 0x1BF0,
            NextLevelXP = 0x1BF4,
            Skill = 0x1BF8,
            CharacterPoints = 0x22F8,
            MaxTalentTiers = 0x22FC,
            TrackCreatureMask = 0x2300,
            TrackResourceMask = 0x2304,
            MainhandExpertise = 0x2308,
            OffhandExpertise = 0x230C,
            RangedExpertise = 0x2310,
            CombatRatingExpertise = 0x2314,
            BlockPercentage = 0x2318,
            DodgePercentage = 0x231C,
            ParryPercentage = 0x2320,
            CritPercentage = 0x2324,
            RangedCritPercentage = 0x2328,
            OffhandCritPercentage = 0x232C,
            SpellCritPercentage = 0x2330,
            ShieldBlock = 0x234C,
            ShieldBlockCritPercentage = 0x2350,
            Mastery = 0x2354,
            Amplify = 0x2358,
            Multistrike = 0x235C,
            MultistrikeEffect = 0x2360,
            Readiness = 0x2364,
            Speed = 0x2368,
            Lifesteal = 0x236C,
            Avoidance = 0x2370,
            Sturdiness = 0x2374,
            Cleave = 0x2378,
            Versatility = 0x237C,
            VersatilityBonus = 0x2380,
            PvpPowerDamage = 0x2384,
            PvpPowerHealing = 0x2388,
            ExploredZones = 0x238C,
            RestStateBonusPool = 0x26AC,
            ModDamageDonePos = 0x26B0,
            ModDamageDoneNeg = 0x26CC,
            ModDamageDonePercent = 0x26E8,
            ModHealingDonePos = 0x2704,
            ModHealingPercent = 0x2708,
            ModHealingDonePercent = 0x270C,
            ModPeriodicHealingDonePercent = 0x2710,
            WeaponDmgMultipliers = 0x2714,
            WeaponAtkSpeedMultipliers = 0x2720,
            ModSpellPowerPercent = 0x272C,
            ModResiliencePercent = 0x2730,
            OverrideSpellPowerByAPPercent = 0x2734,
            OverrideAPBySpellPowerPercent = 0x2738,
            ModTargetResistance = 0x273C,
            ModTargetPhysicalResistance = 0x2740,
            LocalFlags = 0x2744,
            LifetimeMaxRank = 0x2748,
            SelfResSpell = 0x274C,
            PvpMedals = 0x2750,
            BuybackPrice = 0x2754,
            BuybackTimestamp = 0x2784,
            YesterdayHonorableKills = 0x27B4,
            LifetimeHonorableKills = 0x27B8,
            WatchedFactionIndex = 0x27BC,
            CombatRatings = 0x27C0,
            PvpInfo = 0x2840,
            MaxLevel = 0x28D0,
            RuneRegen = 0x28D4,
            NoReagentCostMask = 0x28E4,
            GlyphSlots = 0x28F4,
            Glyphs = 0x290C,
            GlyphSlotsEnabled = 0x2924,
            PetSpellPower = 0x2928,
            Researching = 0x292C,
            ProfessionSkillLine = 0x2954,
            UiHitModifier = 0x295C,
            UiSpellHitModifier = 0x2960,
            HomeRealmTimeOffset = 0x2964,
            ModPetHaste = 0x2968,
            SummonedBattlePetGUID = 0x296C,
            OverrideSpellsID = 0x297C,
            LfgBonusFactionID = 0x2980,
            LootSpecID = 0x2984,
            OverrideZonePVPType = 0x2988,
            ItemLevelDelta = 0x298C,
            BagSlotFlags = 0x2990,
            BankBagSlotFlags = 0x29A0,
            InsertItemsLeftToRight = 0x29BC,
        };

        public enum WoWGameObjectFields
        {
            CreatedBy = 0x30,
            DisplayID = 0x40,
            Flags = 0x44,
            ParentRotation = 0x48,
            FactionTemplate = 0x58,
            Level = 0x5C,
            PercentHealth = 0x60,
            SpellVisualID = 0x64,
            StateSpellVisualID = 0x68,
            StateAnimID = 0x6C,
            StateAnimKitID = 0x70,
            StateWorldEffectID = 0x74,
        };

        public enum WoWDynamicObjectFields
        {
            Caster = 0x30,
            TypeAndVisualID = 0x40,
            SpellID = 0x44,
            Radius = 0x48,
            CastTime = 0x4C,
        };

        public enum WoWCorpseFields
        {
            Owner = 0x30,
            PartyGUID = 0x40,
            DisplayID = 0x50,
            Items = 0x54,
            SkinID = 0xA0,
            FacialHairStyleID = 0xA4,
            Flags = 0xA8,
            DynamicFlags = 0xAC,
            FactionTemplate = 0xB0,
        };

        public enum WoWAreaTriggerFields
        {
            Caster = 0x30,
            Duration = 0x40,
            SpellID = 0x44,
            SpellVisualID = 0x48,
            ExplicitScale = 0x4C,
        };

        public enum WoWSceneObjectFields
        {
            ScriptPackageID = 0x30,
            RndSeedVal = 0x34,
            CreatedBy = 0x38,
            SceneType = 0x48,
        };



    }
}
